# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'FaceAnimation_Pytorch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FaceAnimation_Pytorch
  pod 'LibTorch-Lite', '~>1.9.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  
  pod 'RxSwiftExt'
  pod 'SnapKit'
  
end

target 'FaceAnimation_Pytorch_GPU' do
  use_frameworks!
  pod 'LibTorch-Lite-Nightly'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
end

target 'FaceAnimation_Pytorch_CoreML' do
  use_frameworks!
  
  pod 'LibTorch-Lite', '~>1.9.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  
  pod 'RxSwiftExt'
  pod 'SnapKit'
  
  pod 'OpenCV'
  pod 'TensorFlowLiteSwift', :subspecs => ['CoreML', 'Metal']
  
end
